module.exports = {
    userFormatError:{
        code:"10001",
        message:"用户名或密码为空",
        result:""
    },
    userAlreadyExisted:{
        code:"10002",
        message:"用户名已经存在",
        result:""
    },
    userRegisterError:{
        code:"10003",
        message:"用户注册错误",
        result:""
    },
    userNotExist:{
        code:"10004",
        message:"用户不存在",
        result:""
    },
    userLoginError:{
        code:"10005",
        message:"用户登陆失败",
        result:""
    },
    invalidPassword:{
        code:"10006",
        message:"无效的密码",
        result:""
    },
    tokenExpiredError:{
        code:"10101",
        message:"token过期",
        result:""
    },
    invalidToken:{
        code:"10102",
        message:"token无效",
        result:""
    },
    noPermissionError:{
        code:"10103",
        message:"无管理员权限",
        result:""
    },
    fileUploadError:{
        code:"10201",
        message:"商品图片上传失败",
        result:""
    },
    unSupportedFileType:{
        code:"10202",
        message:"不支持的文件类型",
        result:""
    }
}